---
- name: "Ensure tailscale is up"
  become: True
  block:
  - name: "Add signing key"
    ansible.builtin.apt_key:
      # url this is for raspbian, TODO: make generic
      url: "https://pkgs.tailscale.com/stable/raspbian/buster.gpg"
      state: present
  - name: "Ensure apt repo"
    ansible.builtin.apt_repository:
      repo: "deb https://pkgs.tailscale.com/stable/raspbian buster main"
      state: present
      update_cache: True
      filename: tailscale
  - name: "ensure package"
    ansible.builtin.apt:
      name: tailscale
    register: tailscale_installed
  - name: "enable service so it runs on next restart"
    ansible.builtin.systemd:
      name: "tailscaled"
      enabled: True
  - name: "register the machine if we've newly enabled the service"
    ansible.builtin.shell:
      cmd: "tailscale up --authkey {{ tailscale_auth_key }}"
    when: tailscale_installed.changed
  - name: "get ipv4"
    ansible.builtin.shell:
      cmd: "tailscale ip -4"
    register: tailscale_ip_v4
  - name: "print ipv4"
    ansible.builtin.debug:
      var: tailscale_ip_v4.stdout_lines

