---
- name: Install common "admin" packages
  become: True
  ansible.builtin.apt:
    name:
      - tmux
      - vim
      - curl
      - htop
      - rsync
      - net-tools
      - iftop
      - prometheus-node-exporter

